baseurl = "https://www.opensource-osijek.org/"
title = "Open Source Osijek"
languageCode = "hr"
paginate = 10
theme = "mainroad"
disqusShortname = ""
googleAnalytics = ""
relativeURLs = true
enableGitInfo = true

[permalinks]
    post = "/:year/:month/:day/:title/"

[Params]
    subtitle = "Centar za razvoj programa i sustava baziranih na principima otvorenog kôda"
    description = "Centar za razvoj programa i sustava baziranih na principima otvorenog kôda"
    opengraph = true
    readmore = false
    leftsidebar = false
    authorbox = true
    post_navigation = true
    postSections = ["post"]
    dateformat = "02.01.2006 | 15:04"

[Params.widgets]
    search = true
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
    tags_counter = false
    social_facebook = "OpenSourceOsijek"
    social_github = "opensourceosijek"

[menu]
    [[menu.main]]
        name = "Članci"
        url = "/"
        identifier = "post"
        weight = 1

[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"