baseurl = "https://www.opensource-osijek.org/"
title = "Open Source Osijek"
languageCode = "hr"
paginate = 10
theme = "mainroad"
disqusShortname = ""
googleAnalytics = ""

[permalinks]
    post = "/:year/:month/:day/:title/"

[Params]
    subtitle = "Centar za razvoj programa i sustava baziranih na principima otvorenog kôda"
    description = "Centar za razvoj programa i sustava baziranih na principima otvorenog kôda"
    opengraph = true
    readmore = false
    leftsidebar = false
    authorbox = false
    post_navigation = true
    postSections = ["post"]

[Params.widgets]
    search = true
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
    tags_counter = false
    social_facebook = "username"
    social_twitter = "username"
    social_linkedin = "username"
    social_github = "username"

[menu]
    [[menu.main]]
        name = "Početna"
        url = "/"
        identifier = "post"
        weight = 1

    [[menu.main]]
        name = "O inicijativi"
        url = "/o-inicijativi/"
        identifier = "o-inicijativi"
        weight = 2

    [[menu.main]]
        name = "O nama"
        url = "/o-nama/"
        identifier = "o-nama"
        weight = 3

    [[menu.main]]
        name = "Kategorije"
        url = "/categories/"
        identifier = "categories"
        weight = 4

    [[menu.main]]
        name = "Kontakt"
        url = "/kontakt/"
        identifier = "kontakt"
        weight = 5